# netlify.toml (repo 루트)
[build]
base = "docs"          # ← 여기 중요! docs로 이동한 뒤
command = "yarn build" # docs/package.json의 build 스크립트 실행
publish = "build"      # docs/build 를 자동으로 publish 함

[build.environment]
NODE_VERSION = "20"